
name: "KatDevlin's-website"
output_dir: "."
navbar:
  title: "Kat's Website"
  left:
    - text: "Home"
      href: index.html
    - text: "About Me"
<<<<<<< Updated upstream
      href: about.html
=======
      href: about.html
>>>>>>> Stashed changes
